In [70]:
import numpy as np

a = np.array([[1,2,3,4,5,6]], float)
a2 = np.array([[7],[8],[9],[0],[-1],[12]], float)
print(a)
print("")
print(b)
print("\n\n")

b = a * 2
b2 = a2 * 2
print(b)
print("")
print(b2)
print("\n\n")

c = a + 1
c2 = a2 + 1
print(c)
print("")
print(c2)
print("\n\n")

d = a + a2.T
print(d)
print("\n\n")

e = a - a2.T
print(e)
print("\n\n")


f = a.transpose()
f2 = a2.transpose()
print(f)
print("")
print(f2)
print("\n\n")

g = np.outer(a, a2)
print(g)
print("\n\n")

[[1. 2. 3. 4. 5. 6.]]

[[ 2.  4.  6.  8. 10. 12.]]



[[ 2.  4.  6.  8. 10. 12.]]

[[14.]
 [16.]
 [18.]
 [ 0.]
 [-2.]
 [24.]]



[[2. 3. 4. 5. 6. 7.]]

[[ 8.]
 [ 9.]
 [10.]
 [ 1.]
 [ 0.]
 [13.]]



[[ 8. 10. 12.  4.  4. 18.]]



[[-6. -6. -6.  4.  6. -6.]]



[[1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]]

[[ 7.  8.  9.  0. -1. 12.]]



[[ 7.  8.  9.  0. -1. 12.]
 [14. 16. 18.  0. -2. 24.]
 [21. 24. 27.  0. -3. 36.]
 [28. 32. 36.  0. -4. 48.]
 [35. 40. 45.  0. -5. 60.]
 [42. 48. 54.  0. -6. 72.]]



