In [14]:
import numpy as np

a = np.array([[1,2,3], [4,0,6], [7,8,9]])
a2 = np.linalg.inv(a)
print(a)
print("")
print(a2)

[[1 2 3]
 [4 0 6]
 [7 8 9]]

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


In [13]:
import numpy as np

a = np.array([[1,2,3,4], [3,6,9,12], [6,12,18,24], [0.5,1,1.5,2]])
print(a)
print("")
print("Ранг матрицы a:", np.linalg.matrix_rank(a, 0.0001))

[[ 1.   2.   3.   4. ]
 [ 3.   6.   9.  12. ]
 [ 6.  12.  18.  24. ]
 [ 0.5  1.   1.5  2. ]]

Ранг матрицы a: 1
