In [38]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9], [0,-1,12]], float)
print(a)
print("\n\n")

k, l = 2, 3
b = (k*l)*a
b2 = k*(l*a)
print(b)
print("")
print(b2)
print("\n\n")

c = k*np.add(a, b)
c2 = np.add(k*a, k*b)
print(c)
print("")
print(c2)
print("\n\n")

d = (k+l)*a
d2 = np.add(k*a, l*a)
print(d)
print("")
print(d2)
print("\n\n")

b1 = b.transpose()
e = np.dot(np.dot(a, b1), c)
e2 = np.dot(a, np.dot(b1, c))
print(e)
print("")
print(e2)
print("\n\n")

c1 = c.transpose()
f = np.dot(np.add(a, b), c1)
f2 = np.add(np.dot(a, c1), np.dot(b, c1))
print(f)
print("")
print(f2)
print("\n\n")

g = np.dot(a, np.add(b1, c1))
g2 = np.add(np.dot(a, b1), np.dot(a, c1))
print(g)
print("")
print(g2)
print("\n\n")

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [ 0. -1. 12.]]



[[ 6. 12. 18.]
 [24. 30. 36.]
 [42. 48. 54.]
 [ 0. -6. 72.]]

[[ 6. 12. 18.]
 [24. 30. 36.]
 [42. 48. 54.]
 [ 0. -6. 72.]]



[[ 14.  28.  42.]
 [ 56.  70.  84.]
 [ 98. 112. 126.]
 [  0. -14. 168.]]

[[ 14.  28.  42.]
 [ 56.  70.  84.]
 [ 98. 112. 126.]
 [  0. -14. 168.]]



[[ 5. 10. 15.]
 [20. 25. 30.]
 [35. 40. 45.]
 [ 0. -5. 60.]]

[[ 5. 10. 15.]
 [20. 25. 30.]
 [35. 40. 45.]
 [ 0. -5. 60.]]



[[ 41328.  46536.  91728.]
 [100296. 114072. 206640.]
 [159264. 181608. 321552.]
 [ 84168.  88872. 264096.]]

[[ 41328.  46536.  91728.]
 [100296. 114072. 206640.]
 [159264. 181608. 321552.]
 [ 84168.  88872. 264096.]]



[[ 1372.  3136.  4900.  3332.]
 [ 3136.  7546. 11956.  6566.]
 [ 4900. 11956. 19012.  9800.]
 [ 3332.  6566.  9800. 14210.]]

[[ 1372.  3136.  4900.  3332.]
 [ 3136.  7546. 11956.  6566.]
 [ 4900. 11956. 19012.  9800.]
 [ 3332.  6566.  9800. 14210.]]



[[ 280.  640. 1000.  680.]
 [ 640. 1540. 2440. 1340.]
 [10