In [39]:
import numpy as np

A = np.array([[1,2,3], [4,0,6], [7,8,9]])
B = np.array([[12,2,1]])
C = np.concatenate((A, B.T), axis=1)
print(C)
print("")
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[ 1  2  3 12]
 [ 4  0  6  2]
 [ 7  8  9  1]]



(3, 3)

In [37]:
import numpy as np

A = np.array([[1,2,3], [4,0,6], [7,8,9]])
B = np.array([12,2,1])
print(np.linalg.solve(A, B))
print("")
np.linalg.lstsq(A, B, rcond=None)

[-9.2         0.9         6.46666667]



(array([-9.2       ,  0.9       ,  6.46666667]),
 array([], dtype=float64),
 3,
 array([15.63376871,  3.81768041,  1.00528221]))