In [2]:
import numpy as np
import scipy
import scipy.linalg

A = np.array([[ 1, 2,  3],
              [ 2, 16, 21],
              [ 4, 28, 73]])
P, L, U = scipy.linalg.lu(A)
print(A)
print(P)
print(L)
print(U)
print(np.dot(np.dot(P, L), U))

[[ 1  2  3]
 [ 2 16 21]
 [ 4 28 73]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[ 1.  2.  3.]
 [ 2. 16. 21.]
 [ 4. 28. 73.]]
